"""create telemetry_points

Revision ID: e1bb6eeec8e9
Revises: 33845fa49443
Create Date: 2026-04-15 01:33:35.214057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1bb6eeec8e9'
down_revision: Union[str, Sequence[str], None] = '33845fa49443'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('satellite_id', sa.UUID(), nullable=False),
    sa.Column('parameter', sa.String(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('telemetry',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('satellite_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('velocity', sa.Float(), nullable=False),
    sa.Column('altitude', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['satellite_id'], ['satellites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_satellite_timestamp', 'telemetry', ['satellite_id', sa.literal_column('timestamp DESC')], unique=False)
    op.create_index(op.f('ix_telemetry_satellite_id'), 'telemetry', ['satellite_id'], unique=False)
    op.create_table('telemetry_parameters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('satellite_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('min_value', sa.Float(), nullable=True),
    sa.Column('max_value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['satellite_id'], ['satellites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('telemetry_points',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('satellite_id', sa.UUID(), nullable=False),
    sa.Column('parameter_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['parameter_id'], ['telemetry_parameters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['satellite_id'], ['satellites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'parameter_id', name='uq_event_parameter')
    )
    op.create_index('idx_sat_param_time', 'telemetry_points', ['satellite_id', 'parameter_id', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_sat_param_time', table_name='telemetry_points')
    op.drop_table('telemetry_points')
    op.drop_table('telemetry_parameters')
    op.drop_index(op.f('ix_telemetry_satellite_id'), table_name='telemetry')
    op.drop_index('idx_satellite_timestamp', table_name='telemetry')
    op.drop_table('telemetry')
    op.drop_table('alerts')
    # ### end Alembic commands ###
