"""add event_id to telemetry_points

Revision ID: f43242d5663f
Revises: 85764519d123
Create Date: 2026-04-15 02:37:59.877143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f43242d5663f'
down_revision: Union[str, Sequence[str], None] = '85764519d123'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_satellite_timestamp'), table_name='telemetry')
    op.drop_index(op.f('ix_telemetry_satellite_id'), table_name='telemetry')
    op.drop_table('telemetry')
    op.drop_index(op.f('idx_sat_param_time'), table_name='telemetry_points')
    op.drop_constraint(op.f('uq_event_parameter'), 'telemetry_points', type_='unique')
    op.drop_constraint(op.f('telemetry_points_satellite_id_fkey'), 'telemetry_points', type_='foreignkey')
    op.drop_constraint(op.f('telemetry_points_parameter_id_fkey'), 'telemetry_points', type_='foreignkey')
    op.create_foreign_key(None, 'telemetry_points', 'telemetry_parameters', ['parameter_id'], ['id'])
    op.create_foreign_key(None, 'telemetry_points', 'satellites', ['satellite_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'telemetry_points', type_='foreignkey')
    op.drop_constraint(None, 'telemetry_points', type_='foreignkey')
    op.create_foreign_key(op.f('telemetry_points_parameter_id_fkey'), 'telemetry_points', 'telemetry_parameters', ['parameter_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('telemetry_points_satellite_id_fkey'), 'telemetry_points', 'satellites', ['satellite_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('uq_event_parameter'), 'telemetry_points', ['event_id', 'parameter_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_sat_param_time'), 'telemetry_points', ['satellite_id', 'parameter_id', 'timestamp'], unique=False)
    op.create_table('telemetry',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('satellite_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('temperature', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('velocity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('altitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['satellite_id'], ['satellites.id'], name=op.f('telemetry_satellite_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('telemetry_pkey'))
    )
    op.create_index(op.f('ix_telemetry_satellite_id'), 'telemetry', ['satellite_id'], unique=False)
    op.create_index(op.f('idx_satellite_timestamp'), 'telemetry', ['satellite_id', sa.literal_column('timestamp DESC')], unique=False)
    # ### end Alembic commands ###
