"""add conversation title

Revision ID: fb0deac58366
Revises: de3e3aac9f59
Create Date: 2026-06-18 00:14:28.578093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb0deac58366'
down_revision: Union[str, Sequence[str], None] = 'de3e3aac9f59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'title')
    # ### end Alembic commands ###
